{{- if .Values.outpost.authKey.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "subimage-outpost.authKeySecretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "subimage-outpost.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $authKey := required "outpost.authKey.value is required when outpost.authKey.secret.create is true" .Values.outpost.authKey.value }}
  {{- if not (contains "ephemeral=true" $authKey) }}
  {{ .Values.outpost.authKey.secret.key }}: {{ printf "%s?ephemeral=true" $authKey | quote }}
  {{- else }}
  {{ .Values.outpost.authKey.secret.key }}: {{ $authKey | quote }}
  {{- end }}
{{- end }}
